# Generated by Django 3.2.9 on 2022-01-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
