# Generated by Django 3.2.9 on 2022-01-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('assembled', 'Собран'), ('basket', 'Статус корзины'), ('cancelled', 'Отменен'), ('confirmed', 'Подтвержден'), ('delivered', 'Доставлен'), ('new', 'Новый'), ('sent', 'Отправлен')], default='basket', max_length=15, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='status',
            field=models.CharField(choices=[('assembled', 'Собрана'), ('cancelled', 'Отменена'), ('confirmed', 'Подтверждена'), ('delivered', 'Доставлена'), ('new', 'Новая'), ('sent', 'Отправлена')], default='new', max_length=15, verbose_name='Состояние'),
        ),
    ]
