# Generated by Django 4.0.1 on 2022-01-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_shops'),
        ('orders', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='ordercontent',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='products.productinfo', verbose_name='Продукт'),
        ),
    ]
