# Generated by Django 4.0 on 2022-01-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_products_order_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.AddField(
            model_name='order',
            name='parent_order_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Внутренний идентификатор категории'),
        ),
    ]
