# Generated by Django 4.0.1 on 2022-02-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_positions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders list'},
        ),
        migrations.AlterModelOptions(
            name='ordercontent',
            options={'verbose_name': 'order content', 'verbose_name_plural': 'orders contents list'},
        ),
    ]
