# Generated by Django 4.0 on 2022-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_shop_order_parent_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercontent',
            name='status',
            field=models.CharField(choices=[('assembled', 'Собрана'), ('canceled', 'Отменена'), ('confirmed', 'Подтверждена'), ('delivered', 'Доставлена'), ('new', 'Новая'), ('sent', 'Отправлена')], default='new', max_length=15, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('assembled', 'Собран'), ('basket', 'Статус корзины'), ('canceled', 'Отменен'), ('confirmed', 'Подтвержден'), ('delivered', 'Доставлен'), ('new', 'Новый'), ('sent', 'Отправлен')], default='basket', max_length=15, verbose_name='Состояние'),
        ),
    ]
