# Generated by Django 4.0.1 on 2022-01-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_shops'),
        ('shops', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Список категорий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(through='products.ProductInfo', to='shops.Shop', verbose_name='Список магазинов'),
        ),
    ]
