# Generated by Django 4.0.1 on 2022-02-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productinfo_product_alter_productinfo_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['-name'], 'verbose_name': 'parameter', 'verbose_name_plural': 'parameters list'},
        ),
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'verbose_name': 'product parameter', 'verbose_name_plural': 'products parameters list'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'product', 'verbose_name_plural': 'products list'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'product info', 'verbose_name_plural': 'products infos list'},
        ),
    ]
