# Generated by Django 4.0.1 on 2022-01-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('categories', '0003_alter_category_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='Магазин'),
        ),
    ]
