# Generated by Django 4.0.1 on 2022-02-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_shopcategory_category_alter_shopcategory_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories list'},
        ),
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'verbose_name': 'shop category', 'verbose_name_plural': 'shops categories list'},
        ),
    ]
